### ISSUE TITLE
Bad access crash

### ISSUE THREAD

**Issue by TMSantos** [toeydevelopment/key_enclave#1]
Hi!

I'm getting crash for IOS when generating key pair, at this line:

`guard let privateKey = SecKeyCreateRandomKey(attributes as CFDictionary,&error) else {
                    print("ERORR OCCURED GENERATE KEY FAILED")
                    throw SecureError.GenerateKeyPair
                }`

Any ideia why this might happen?

screenshot:
<img width="900" alt="Screenshot 2020-08-09 at 16 27 56" src="https://user-images.githubusercontent.com/5798822/89735870-57519700-da5d-11ea-8227-a7ecf6fa3e8f.png">

**Comment by TMSantos** [comment]
Maybe is because I'm using simulator, do you know if it won't work on simulator?

**Comment by toeydevelopment** [comment]
Cannot used it in simulator

Because my package generate private key and store in hardware that why simulator can do that 

You must have physical device to use that

Sorry for inconvenience

**Comment by TMSantos** [comment]
thanks for clarification, have a nice day!
