### ISSUE TITLE
Possible to add custom flags?

### ISSUE THREAD

**Issue by Amnesthesia** [toeydevelopment/key_enclave#3]
We specifically need to add the iOS flags: `kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly`, `kSecAccessControlBiometryCurrentSet` and `kSecAccessControlPrivateKeyUsage`, and out of these only the first one is default with this plugin; would it be possible to add arguments to support additional flags?

**Comment by toeydevelopment** [comment]
Sure !


Thank you so much

**Comment by Amnesthesia** [comment]
I was trying to submit a PR for it, but turns out learning Swift on the fly was way more difficult than I expected - thanks a lot for the quick reply @toeydevelopment!

**Comment by Amnesthesia** [comment]
Any progress on this?

**Comment by toeydevelopment** [comment]
kSecAttrAccessibleWhenPasscodeSetThisDeviceOnly 
 is deprecated 
ref : https://developer.apple.com/documentation/security/ksecattraccessiblewhenpasscodesetthisdeviceonly

this is all flags that supported 

https://developer.apple.com/documentation/security/certificate_key_and_trust_services/keys/key_generation_attributes


Sorry for the late reply.

**Comment by Amnesthesia** [comment]
Hey @toeydevelopment, yes but that's not the flag we'd like to set, we're looking to set: `kSecAccessControlPrivateKeyUsage` and `kSecAccessControlBiometryCurrentSet`, would be nice if you could set flags from flutter :)
